services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    # ports:
    #   - 5432:8493
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
