on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Name of the target environment
      ref:
        type: string
        required: true
        description: The tag or SHA to checkout
