name: Build and deploy
env:
  GCP_PROJECT_ID: 'ancient-sunspot-352209'
  CLOUD_RUN_SERVICE: 'cloud-run-deploy'
  GCP_REGION: eu-west1
  WORKLOAD_IDENTITY_PROVIDER: 'projects/747268936816/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc'
  ARTIFACT_REGISTRY: "europe-west1-docker.pkg.dev/ancient-sunspot-352209/cloud-run-deploy-repo"
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - run: npm run test:unit
  deploy:
    # if: ${{ github.ref == 'refs/head/main' || github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
      - uses: 'google-github-actions/setup-gcloud@v2'
      - run: gcloud auth configure-docker europe-west1-docker.pkg.dev
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "${{ env.ARTIFACT_REGISTRY }}/cloud-run-deploy:${{ github.sha }}"
      - name: Deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.CLOUD_RUN_SERVICE }}
          image: "${{ env.ARTIFACT_REGISTRY }}/cloud-run-deploy:${{ github.sha }}"
          region: ${{ env.GCP_REGION }}
    permissions:
      id-token: write
      contents: read
